In [1]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [2]:
import numpy as ab
list = [10,20,30,40]
arr = ab.array(list,dtype = 'U32')
print(arr)

['10' '20' '30' '40']


In [4]:
import numpy as ab
list = [10,20,30,40]
arr = ab.array(list)
type(arr)

numpy.ndarray

In [5]:
import numpy as ab
list = [[10,20,30] , [40,50,60] , [70,80,90]]
arr = ab.array(list)
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [7]:
import numpy as np
arr = np.arange(1,8)
print(arr)

[1 2 3 4 5 6 7]


In [8]:
import numpy as np
arr = np.arange(11,17).reshape(2,3)
print(arr)

[[11 12 13]
 [14 15 16]]


In [7]:
import numpy as np
arr = np.zeros(4)
print(arr)

[0. 0. 0. 0.]


In [10]:
import numpy as np
a = np.array([2,4,6])
b = np.array([1,3,5])
print(a+b)

[ 3  7 11]


In [11]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
arr.ndim

2

In [12]:
import numpy as np
list = [2,4,6,8,9]
arr = np.array(list)
arr.shape

(5,)

In [13]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[1])
print(arr[-2])

2
4


In [14]:
import numpy as np
arr = np.array([[2,4,6,8],[1,3,5,7]])
print(arr[1,2])
print(arr[0,:])
print(arr[1,:])

5
[2 4 6 8]
[1 3 5 7]


In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[0:5:2])
print(arr[-1:-7:-1])
print(arr[::2])
print(arr[::-2])

[2 3 4 5]
[1 3 5]
[7 6 5 4 3 2]
[1 3 5 7]
[7 5 3 1]


In [3]:
import numpy as np
arr = np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print(arr[2:])
print(arr[1:3 , 1:3])

[[ 90 100 110 120]]
[[ 60  70]
 [100 110]]


In [5]:
import numpy as np
a = np.array([[1 , 2],[3,4]])
b= np.array([[5,6],[7,8]])
print(a+b)
print(b-a)
print(a*b)
print(a/b)
print(a @ b)  #matrix calculation
print(a // b) # Floor division
print(a** b)  #Exponentiation
print(a % b ) #modulo (remainder)
print(a.transpose())

[[ 6  8]
 [10 12]]
[[4 4]
 [4 4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]
[[0 0]
 [0 0]]
[[    1    64]
 [ 2187 65536]]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [6]:
import numpy as np
arr = np.array([1,2,3,4])
arr>3

array([False, False, False,  True])

In [9]:
import numpy as np
arr = np.eye(3)
print(arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
import numpy as np
arr = np.linspace(2, 8, num=4)
print(arr)

[2. 4. 6. 8.]


In [16]:
import numpy as np
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

print("Original Array:")
print(arr)

print("\nSum of each column (axis=0):")
print(np.sum(arr, axis=0))

print("\nSum of each row (axis=1):")
print(np.sum(arr, axis=1))


Original Array:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

Sum of each column (axis=0):
[150 180 210 240]

Sum of each row (axis=1):
[100 260 420]


In [19]:
import numpy as np
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])
print("\nMax of each column (axis=0):")
print(np.max(arr, axis=0))

print("\nMax of each row (axis=1):")
print(np.max(arr, axis=1))


Max of each column (axis=0):
[ 90 100 110 120]

Max of each row (axis=1):
[ 40  80 120]


In [21]:
import numpy as np
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])
print("\nMean of each column (axis=0):")
print(np.mean(arr,axis=0))

print("\nMean of each row (axis=1):")
print(np.mean(arr,axis=1))


Mean of each column (axis=0):
[50. 60. 70. 80.]

Mean of each row (axis=1):
[ 25.  65. 105.]
